### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by madtomic** [Zbob750/ClientDeny#1]
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ClientDeny 1.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ClientDeny ---
[INFO]
[INFO] --- git-commit-id-plugin:2.1.9:revision (default) @ ClientDeny ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.562 s
[INFO] Finished at: 2015-04-22T22:16:41-04:00
[INFO] Final Memory: 6M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.9:rev
ision (default) on project ClientDeny: .git directory could not be found! Please
 specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

**Comment by madtomic** [comment]
Please advices on how to build it. I am using Maven3.3.1  Thank you.

I found this in pom.xml
dotGitDirectory${project.basedir}/.git

**Comment by zachbr** [comment]
It appears that you used GitHub's "Download as ZIP" button instead of using git's clone feature.
For whatever reason, GitHub doesn't include the actual git repository information along with the rest of the source in that zip. We need that repo as part of the build process as we attach the last commit hash to the description of the plugin, however it's not something that is mission critical and the plugin will work fine without the information.

You can fix this by either a) cloning it with git or a git tool (which is what I'd recommend and will support) or you can b) open up the pom.xml file and remove the git commit id plugin then re-run your maven build.

However, I only intend on supporting option a) as I consider this an issue with GitHub rather than one with the repo, so I will not be making any changes here. Thanks for reporting it anyway.

**Comment by madtomic** [comment]
Thank you for the advices.
